{{- if .Values.bootnode.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "bootnode.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "prysm.name" . }}
    chart: {{ template "prysm.chart" . }}
    component: "bootnode"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
{{- end }}
