{{- if .Values.bootnode.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "bootnode.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "prysm.name" . }}
    chart: {{ template "prysm.chart" . }}
    component: "bootnode"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  replicas: 1
  minReadySeconds: 15
  selector:
    matchLabels:
      app: {{ template "prysm.name" . }}
      component: "bootnode"
      release: {{ .Release.Name | quote }}
  template:
    metadata:
      labels:
        app: {{ template "prysm.name" . }}
        release: {{ .Release.Name | quote }}
        component: "bootnode"
    {{- if .Values.bootnode.privateKey }}
      annotations:
        checksum/bootnode-secret: {{ include (print $.Template.BasePath "/bootnode-secret.yaml") . | sha256sum }}
    {{- end }}
    spec:
    {{- with .Values.securityContext }}
      securityContext:
        {{ toYaml . | nindent 8 | trim }}
    {{- end }}
      serviceAccountName: {{ template "bootnode.fullname" . }}
      priorityClassName: {{ .Values.bootnode.priorityClassName | quote }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.bootnode.image.repository }}:{{ .Values.bootnode.image.tag }}"
          imagePullPolicy: {{ .Values.bootnode.image.pullPolicy }}
          args:
            - "--discv5-port=4000"
            - "--metrics-port=5000"
          {{- range .Values.bootnode.extraFlags }}
            - {{ . | quote }}
          {{- end }}
        {{- if .Values.bootnode.privateKey }}
            - "--private=$(PRIVATE_KEY)"
          envFrom:
            - secretRef:
                name: {{ template "bootnode.fullname" . }}
        {{- end }}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
        {{- with .Values.bootnode.resources }}
          resources:
            {{ toYaml . | nindent 12 | trim }}
        {{- end }}
          ports:
            - name: discv5
              containerPort: 4000
              protocol: TCP
            - name: metrics
              containerPort: 5000
              protocol: TCP
{{- end }}
