{{- if .Values.miner.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "miner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "geth.name" . }}
    chart: {{ template "geth.chart" . }}
    component: "miner"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
{{- range $index, $account := .Values.miner.accounts }}
  {{ template "miner.fullname" $ }}-{{ $index }}: {{ $account.privateKey | b64enc | quote }}
  {{ template "miner.fullname" $ }}-{{ $index }}-pass: {{ $account.password | b64enc | quote }}
{{- end }}
{{- end }}
