{{- if .Values.node.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "node.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "geth.name" . }}
    chart: {{ template "geth.chart" . }}
    component: "node"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
{{- end }}
