apiVersion: v2
name: oracle
version: 0.1.0
kubeVersion: "^1.14.0-0"
description: The StakeWise application for submitting off-chain data to smart contracts.
type: application
keywords:
  - ethereum
  - blockchain
  - staking
home: https://stakewise.io/
sources:
  - https://github.com/stakewise/oracle/
maintainers:
  - name: Dmitri Tsumak
    email: dmitri@stakewise.io
appVersion: 0.1.0
