kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ template "oracle.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "oracle.name" . }}
    chart: {{ template "oracle.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ template "oracle.name" . }}
      release: {{ .Release.Name | quote }}
  template:
    metadata:
      labels:
        app: {{ template "oracle.name" . }}
        release: {{ .Release.Name | quote }}
      annotations:
        checksum/oracle-secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        checksum/oracle-configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
    {{- if .Values.tolerations }}
      tolerations:
        {{ tpl .Values.tolerations . | nindent 8 | trim }}
    {{- end }}
    {{- if .Values.affinity }}
      affinity:
        {{ tpl .Values.affinity . | nindent 8 | trim }}
    {{- end }}
    {{- with .Values.securityContext }}
      securityContext:
        {{ toYaml . | nindent 8 | trim }}
    {{- end }}
      serviceAccountName: {{ template "oracle.fullname" . }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
    {{- if .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ template "oracle.fullname" . }}
            - secretRef:
                name: {{ template "oracle.fullname" . }}
        {{- with .Values.resources }}
          resources:
            {{ toYaml . | nindent 12 | trim }}
        {{- end }}
