apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ template "oracle.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "oracle.name" . }}
    chart: {{ template "oracle.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
rules:
  - apiGroups: ["extensions"]
    resources: ["podsecuritypolicies"]
    verbs: ["use"]
    resourceNames:
      - {{ template "oracle.fullname" . }}
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames:
      - {{ template "oracle.fullname" . }}
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames:
      - {{ template "oracle.fullname" . }}
    verbs: ["get"]
