apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "reporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "reporter.name" . }}
    chart: {{ template "reporter.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
data:
  # https://github.com/notifiers/notifiers/issues/328
  USERNAME: user

  # connections
  WEB3_WS_ENDPOINT: {{ .Values.settings.web3WsEndpoint | quote }}
  WEB3_HTTP_ENDPOINT: {{ .Values.settings.web3HttpEndpoint | quote }}
  BEACON_CHAIN_RPC_ENDPOINT: {{ .Values.settings.beaconChainRpcEndpoint | quote }}

  # middlewares
  INJECT_POA_MIDDLEWARE: {{ .Values.settings.injectPOAMiddleware | quote }}
  INJECT_STALE_CHECK_MIDDLEWARE: {{ .Values.settings.injectStaleCheckMiddleware | quote }}
  STALE_CHECK_MIDDLEWARE_ALLOWABLE_DELAY: {{ .Values.settings.staleCheckMiddlewareAllowableDelay | quote }}
  INJECT_RETRY_REQUEST_MIDDLEWARE: {{ .Values.settings.injectRetryRequestMiddleware | quote }}
  INJECT_LOCAL_FILTER_MIDDLEWARE: {{ .Values.settings.injectLocalFilterMiddleware | quote }}
  APPLY_GAS_PRICE_STRATEGY: {{ .Values.settings.applyGasPriceStrategy | quote }}
  MAX_TX_WAIT_SECONDS: {{ .Values.settings.maxTxWaitSeconds | quote }}

  # reporter balance
  BALANCE_WARNING_THRESHOLD: {{ .Values.settings.balanceWarningThreshold | quote }}
  BALANCE_ERROR_THRESHOLD: {{ .Values.settings.balanceErrorThreshold | quote }}

  # transactions
  TRANSACTION_TIMEOUT: {{ .Values.settings.transactionTimeout | quote }}

  # contracts
  POOL_CONTRACT_ADDRESS: {{ .Values.settings.poolContractAddress | quote }}
  REWARD_ETH_CONTRACT_ADDRESS: {{ .Values.settings.rewardEthContractAddress | quote }}
  STAKED_ETH_CONTRACT_ADDRESS: {{ .Values.settings.stakedEthContractAddress | quote }}
  BALANCE_REPORTERS_CONTRACT_ADDRESS: {{ .Values.settings.balanceReportersContractAddress | quote }}
